In [2]:
# 전처리에 사용
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import seaborn as sns
import numpy as np
# 머신러닝에 사용
from sklearn.model_selection import cross_validate
# 특성 중요도
from sklearn.inspection import permutation_importance
#훈련모델
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
# 훈련모델 평가를 위한 metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import plot_confusion_matrix
# 한글폰트 설정
plt.rc("font", family = "Malgun Gothic")
# 마이너스값에 대한 기호표시
plt.rcParams["axes.unicode_minus"] = False

In [3]:
# 데이터 읽어 들이기
file_name = "./data/01_org/final_df.csv"
df_data = pd.read_csv(file_name)
df_data

         pH   Temp  Voltage  QC
0      2.15  43.15    19.74   0
1      2.08  40.13    18.01   0
2      2.18  43.46    18.73   0
3      1.99  41.72    16.75   0
4      1.85  43.65    18.02   0
...     ...    ...      ...  ..
50089  2.05  42.84    15.38   0
50090  1.91  42.64    19.08   0
50091  2.11  44.09    18.14   0
50092  1.92  43.95    17.96   0
50093  1.81  44.11    19.22   0

[50094 rows x 4 columns]